- name: variables form prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your username?
    private: false
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "Hello, your username is {{ username }}"


