- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install {{ item }}
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - mysql
    - zip