- name: functions
  hosts: local
  connection: local
  vars:
    fruits: apple,banana,orange
    tags:
      Application: payment
      Environment: dev
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello, {{ name | default('Rahul')}}"
  
  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ fruits | split(',') }}"
  
  - name: convert dict/map to list
    ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"